version: "3"
services:
  sonarqube:
    image: sonarqube
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    ports:
      - ${PORT}:9000
    restart: always
